function poses = eightposes
% 8 pose cases.
poses = [   0, 1; ...
            -1, 1; ...
            -1, 0; ...
            -1, -1; ...
            0, -1; ...
            1, -1; ...
            1, 0; ...
            1, 1];

end