function nodes = graphnodes(num)
if nargin == 0, num = 1; end

nodes = struct( 'isterminal', 0, 'ittype', 0, ...
                'angle', 0, 'loc', zeros(3, 1), 'robs', 0, ...
                'chindices', cell(num, 1), 'feats', cell(num, 1), ...
                'dloc', cell(num, 1), 'dpose', cell(num, 1), ...
                'subidx', cell(num, 1), 'azimuth', 0);

end
