function params = initparam(numscene, numobj)
params = struct('numsamples', 1000, ...
                'pmove', [0 0.1 0 0.3 0.3 0.3 0 0], ...
                'accconst', 5, ...
                'C', 1, ...
                'fncost', 1, ...
                'losstype', 'isolation', ...
                'inference', 'combined', ...
                'evaltrain', false, ...
                'model', emptymodel(numscene, numobj));
end

function model = emptymodel(numscene, numobj)

model = struct( 'itmptns', [], ...
                'itmbase', [], ... % baseidx
                'itmfeatlen', [], ... % baseidx
                'nscene', numscene, ...
                'nobjs', numobj, ...
                'w_or', 0, ...
                'w_oo', zeros(numobj * 2, 1), ...
                'w_os', 0, ...
                'w_iso', zeros(numobj * numscene, 1), ...
                'w_ioo', zeros(2, 1), ...
                'w_iof', zeros(1, 1), ...
                'w_iod', zeros(numobj, 1), ...
                'w_ior', zeros(5*numobj, 1), ...
                'ow_edge', [-Inf 0.0500 0.3000 1 2 Inf], ...
                'w', zeros(18, 1), ...
                'commonground', 1, ...
                'feattype', 'itm_v1', ...
                'objmodel', objmodels());

assert(length(model.objmodel) == numobj);
end