function pg = parsegraph(num)
if nargin == 0
    num = 1;
end

if(1)
    pg = struct('scenetype', cell(num, 1), ...
                'layoutidx', cell(num, 1), ...
                'camheight', cell(num, 1), ...
                'childs', cell(num, 1), ...
                'subidx', cell(num, 1), ...
                'objscale', [], ...
                'lkhood', 0, ...
                'loss', 0);
else
    pg = struct('scenetype', cell(num, 1), ...
                'layoutidx', cell(num, 1), ...
                'camheight', cell(num, 1), ...
                'childs', cell(num, 1), ...
                'objscale', [], ...
                'lkhood', 0, ...
                'loss', 0);
end
end
