function poses = twentyfourposes
% 24 pose cases.
poses = [   0, 1; ...
            -1, 1; ...
            -1, 0; ...
            -1, -1; ...
            0, -1; ...
            1, -1; ...
            1, 0; ...
            1, 1];

assert(size(poses, 1) == 24);
end