function cache = mcmccache(numcl, numlayout)
cache = struct( 'inset', false(numcl, 1), ...
                'swset', [], ...
                'szswset', zeros(numcl, 1), ...
                'playout', zeros(numlayout, 1), ...
                'clayout', zeros(numlayout, 1), ...
                'padd', zeros(numcl, 1));
            
cache.swset = cell(numcl, 1);

end